<?php
namespace App\Services;
use App\Models\Integration;
use Illuminate\Support\Facades\{Http,DB};
class AiGateway{
 function providers():array{return ['openai'=>['models'=>['gpt-5-mini','gpt-4.1-mini']],'anthropic'=>['models'=>['claude-sonnet-4-5','claude-haiku-4-5']],'gemini'=>['models'=>['gemini-2.5-flash','gemini-2.5-pro']],'groq'=>['models'=>['llama-3.3-70b-versatile','openai/gpt-oss-120b']],'mistral'=>['models'=>['mistral-small-latest','mistral-large-latest']],'openrouter'=>['models'=>['openai/gpt-4.1-mini','anthropic/claude-sonnet-4']],'bazaarlink'=>['models'=>[]]];}
 function active(?string $provider=null):Integration{$q=Integration::where('type','ai')->where('enabled',true);if($provider)$q->where('provider',$provider);$item=$q->orderByDesc('updated_at')->first();abort_unless($item,503,'No enabled AI provider. Configure one in Admin > API Keys.');return $item;}
 function chat(string $prompt,string $feature='assistant',?int $userId=null,?string $provider=null):array{$cfg=$this->active($provider);$started=microtime(true);try{$answer=$this->request($cfg,$prompt);DB::table('ai_usage')->insert(['user_id'=>$userId,'provider'=>$cfg->provider,'model'=>$cfg->model,'feature'=>$feature,'latency_ms'=>(int)((microtime(true)-$started)*1000),'success'=>true,'created_at'=>now()]);return ['answer'=>$answer,'provider'=>$cfg->provider,'model'=>$cfg->model];}catch(\Throwable $e){DB::table('ai_usage')->insert(['user_id'=>$userId,'provider'=>$cfg->provider,'model'=>$cfg->model,'feature'=>$feature,'latency_ms'=>(int)((microtime(true)-$started)*1000),'success'=>false,'error'=>mb_substr($e->getMessage(),0,500),'created_at'=>now()]);throw $e;}}
 private function request(Integration $c,string $prompt):string{$key=$c->secret;$model=$c->model;
  if($c->provider==='anthropic'){$r=Http::timeout(45)->withHeaders(['x-api-key'=>$key,'anthropic-version'=>'2023-06-01'])->post('https://api.anthropic.com/v1/messages',['model'=>$model,'max_tokens'=>1800,'messages'=>[['role'=>'user','content'=>$prompt]]]);$r->throw();return (string)data_get($r->json(),'content.0.text');}
  if($c->provider==='gemini'){$r=Http::timeout(45)->post('https://generativelanguage.googleapis.com/v1beta/models/'.rawurlencode($model).':generateContent?key='.rawurlencode($key),['contents'=>[['parts'=>[['text'=>$prompt]]]]]);$r->throw();return (string)data_get($r->json(),'candidates.0.content.parts.0.text');}
  $urls=['openai'=>'https://api.openai.com/v1/chat/completions','groq'=>'https://api.groq.com/openai/v1/chat/completions','mistral'=>'https://api.mistral.ai/v1/chat/completions','openrouter'=>'https://openrouter.ai/api/v1/chat/completions','bazaarlink'=>'https://api.bazaarlink.ai/v1/chat/completions'];$r=Http::timeout(45)->withToken($key)->post($urls[$c->provider]??$urls['openai'],['model'=>$model,'messages'=>[['role'=>'system','content'=>'You are CVPilot, a concise career assistant. Never invent candidate experience.'],['role'=>'user','content'=>$prompt]],'temperature'=>0.3]);$r->throw();return (string)data_get($r->json(),'choices.0.message.content');
 }
 function test(Integration $c):array{$answer=$this->request($c,'Reply with exactly: CVPilot connection ready');return ['ok'=>true,'message'=>mb_substr($answer,0,120)];}
}
