<?php
namespace App\Services;
use App\Models\Integration;
use Illuminate\Support\Facades\Http;
class JobSearchService{
 function search(array $d):array{$provider=$d['provider']??null;$cfg=$provider?Integration::where('type','jobs')->where('provider',$provider)->where('enabled',true)->first():Integration::where('type','jobs')->where('enabled',true)->orderByDesc('updated_at')->first();if($cfg)return match($cfg->provider){'jsearch'=>$this->jsearch($cfg,$d),'adzuna'=>$this->adzuna($cfg,$d),'jooble'=>$this->jooble($cfg,$d),default=>$this->arbeitnow($d)};return $this->arbeitnow($d);}
 private function jsearch($c,$d){$query=trim($d['q'].' in '.($d['city']??'').' '.($d['country_name']??$d['country']));$r=Http::timeout(30)->withHeaders(['X-RapidAPI-Key'=>$c->secret,'X-RapidAPI-Host'=>'jsearch.p.rapidapi.com'])->get('https://jsearch.p.rapidapi.com/search',['query'=>$query,'page'=>$d['page']??1,'num_pages'=>1,'date_posted'=>$d['date']??'month']);$r->throw();return ['provider'=>'jsearch','data'=>collect($r->json('data',[]))->map(fn($j)=>['external_id'=>$j['job_id']??null,'title'=>$j['job_title']??'','company'=>$j['employer_name']??'','location'=>implode(', ',array_filter([$j['job_city']??null,$j['job_country']??null])),'description'=>$j['job_description']??'','url'=>$j['job_apply_link']??$j['job_google_link']??'','remote'=>(bool)($j['job_is_remote']??false),'published_at'=>$j['job_posted_at_datetime_utc']??null,'source'=>'JSearch'])->values()->all()];}
 private function adzuna($c,$d){$settings=$c->settings??[];$appId=$settings['app_id']??'';abort_unless($appId,422,'Adzuna app_id is missing.');$cc=strtolower($d['country']);$r=Http::timeout(30)->get("https://api.adzuna.com/v1/api/jobs/$cc/search/".($d['page']??1),['app_id'=>$appId,'app_key'=>$c->secret,'what'=>$d['q'],'where'=>$d['city']??'','results_per_page'=>20,'content-type'=>'application/json']);$r->throw();return ['provider'=>'adzuna','data'=>collect($r->json('results',[]))->map(fn($j)=>['external_id'=>$j['id']??null,'title'=>$j['title']??'','company'=>data_get($j,'company.display_name',''),'location'=>data_get($j,'location.display_name',''),'description'=>$j['description']??'','url'=>$j['redirect_url']??'','remote'=>str_contains(strtolower(($j['title']??'').' '.($j['description']??'')),'remote'),'published_at'=>$j['created']??null,'source'=>'Adzuna'])->values()->all()];}
 private function jooble($c,$d){$r=Http::timeout(30)->post('https://jooble.org/api/'.rawurlencode($c->secret),['keywords'=>$d['q'],'location'=>trim(($d['city']??'').' '.($d['country_name']??$d['country'])),'page'=>$d['page']??1]);$r->throw();return ['provider'=>'jooble','data'=>collect($r->json('jobs',[]))->map(fn($j)=>['external_id'=>$j['id']??null,'title'=>$j['title']??'','company'=>$j['company']??'','location'=>$j['location']??'','description'=>strip_tags($j['snippet']??''),'url'=>$j['link']??'','remote'=>str_contains(strtolower(($j['title']??'').' '.($j['location']??'')),'remote'),'published_at'=>$j['updated']??null,'source'=>$j['source']??'Jooble'])->values()->all()];}
 private function arbeitnow($d){$r=Http::timeout(30)->get('https://www.arbeitnow.com/api/job-board-api',['page'=>$d['page']??1]);$r->throw();$terms=array_filter(preg_split('/\s+/',strtolower($d['q'])),fn($x)=>strlen($x)>2);$items=collect($r->json('data',[]))->filter(fn($j)=>collect($terms)->contains(fn($t)=>str_contains(strtolower(($j['title']??'').' '.implode(' ',$j['tags']??[])),$t)))->map(fn($j)=>['external_id'=>$j['slug']??null,'title'=>$j['title']??'','company'=>$j['company_name']??'','location'=>$j['location']??'','description'=>strip_tags($j['description']??''),'url'=>$j['url']??'','remote'=>(bool)($j['remote']??false),'published_at'=>isset($j['created_at'])?date(DATE_ATOM,$j['created_at']):null,'source'=>'Arbeitnow'])->values()->all();return ['provider'=>'arbeitnow','data'=>$items];}
}
