<?php

namespace Tests\Support;

use Illuminate\Routing\Route as RouteObject;
use Illuminate\Support\Facades\Route;

/** Reads the live route table into the shapes used by the contract test and docs/ROUTES.md. */
class RouteDocs
{
    /** @return array<int, RouteObject> */
    public static function v1(): array
    {
        return array_values(array_filter(iterator_to_array(Route::getRoutes()), fn (RouteObject $r) => str_starts_with($r->uri(), 'api/v1/')));
    }

    /** @return array<int, RouteObject> */
    public static function legacy(): array
    {
        return array_values(array_filter(
            iterator_to_array(Route::getRoutes()),
            fn (RouteObject $r) => str_starts_with($r->uri(), 'api/') && ! str_starts_with($r->uri(), 'api/v1/') && self::deprecation($r) !== null,
        ));
    }

    /** @return array<int, string> every middleware entry, as written in the route files */
    public static function middleware(RouteObject $route): array
    {
        return array_map('strval', $route->gatherMiddleware());
    }

    public static function scope(RouteObject $route): string
    {
        $middleware = self::middleware($route);

        return in_array('admin', $middleware, true) ? 'admin' : (in_array('auth.session', $middleware, true) ? 'auth' : 'public');
    }

    /** The `deprecated` middleware entry of a legacy route (null if it has none). */
    public static function deprecation(RouteObject $route): ?string
    {
        foreach (self::middleware($route) as $entry) {
            if ($entry === 'deprecated' || str_starts_with($entry, 'deprecated:')) {
                return $entry;
            }
        }

        return null;
    }

    public static function successor(RouteObject $route): ?string
    {
        $entry = self::deprecation($route);

        return $entry !== null && str_contains($entry, ':') ? substr($entry, strlen('deprecated:')) : null;
    }

    public static function throttle(RouteObject $route): string
    {
        foreach (self::middleware($route) as $entry) {
            if (str_starts_with($entry, 'throttle:') && $entry !== 'throttle:api') {
                return substr($entry, strlen('throttle:'));
            }
        }

        return '';
    }

    /** @return array<int, string> HTTP methods without HEAD */
    public static function methods(RouteObject $route): array
    {
        return array_values(array_diff($route->methods(), ['HEAD']));
    }

    public static function markdown(): string
    {
        $rows = [];
        foreach (self::v1() as $route) {
            foreach (self::methods($route) as $method) {
                $rows[] = [self::scope($route), substr($route->uri(), 3), $method, self::throttle($route), (string) $route->getName()];
            }
        }
        usort($rows, fn ($a, $b) => [array_search($a[0], ['public', 'auth', 'admin']), $a[1], $a[2]] <=> [array_search($b[0], ['public', 'auth', 'admin']), $b[1], $b[2]]);

        $out = "# API routes\n\n";
        $out .= "Generated by `Tests\\Feature\\Api\\V1RoutesContractTest` from the live route table. Regenerate with `UPDATE_ROUTE_DOCS=1 composer test` and commit the result.\n\n";
        $out .= "All paths are relative to the API origin. Errors use the envelope in [ERRORS.md](ERRORS.md).\n\n";
        $out .= "## /api/v1\n\n| Scope | Method | Path | Throttle (max,minutes,prefix) | Route name |\n| --- | --- | --- | --- | --- |\n";
        foreach ($rows as [$scope, $uri, $method, $throttle, $name]) {
            $out .= "| {$scope} | {$method} | `/api{$uri}` | ".($throttle !== '' ? "`{$throttle}`" : 'shared `api` limiter')." | `{$name}` |\n";
        }

        $legacy = [];
        foreach (self::legacy() as $route) {
            foreach (self::methods($route) as $method) {
                $legacy[] = [$route->uri(), $method, self::successor($route)];
            }
        }
        usort($legacy, fn ($a, $b) => [$a[0], $a[1]] <=> [$b[0], $b[1]]);

        $out .= "\n## Deprecated legacy aliases\n\nEvery alias answers with `Deprecation: true`, a `Link: <successor>; rel=\"successor-version\"` header when it has a successor, and `Sunset` once `API_LEGACY_SUNSET` is set. They are removed in slice S7.\n\n| Method | Legacy path | Successor |\n| --- | --- | --- |\n";
        foreach ($legacy as [$uri, $method, $successor]) {
            $out .= "| {$method} | `/{$uri}` | ".($successor !== null ? "`{$successor}`" : '_legacy only_')." |\n";
        }

        $out .= "\n## Permanent, not versioned\n\n| Method | Path | Why |\n| --- | --- | --- |\n";
        $out .= "| GET | `/api/admin/smtp/microsoft/callback` | OAuth redirect URI registered with Microsoft; never deprecated or moved |\n";
        $out .= "| GET | `/up` | Health check |\n| GET | `/` | Static console page |\n";

        return $out;
    }
}
