<?php
return [
 'paths'=>['api/*'],
 'allowed_methods'=>['*'],
 'allowed_origins'=>array_values(array_unique(array_filter([
  env('FRONTEND_URL'),
  env('FRONTEND_URL_LOCAL'),
  env('APP_URL'),
  'http://localhost:5173',
  'http://127.0.0.1:5173',
  'http://localhost:3000',
  'http://127.0.0.1:3000',
 ]))),
 'allowed_origins_patterns'=>['#^https?://(localhost|127\.0\.0\.1)(:\d+)?$#'],
 'allowed_headers'=>['*'],
 'exposed_headers'=>['Retry-After'],
 'max_age'=>600,
 'supports_credentials'=>true,
];
