<?php
namespace App\Http\Controllers;
use App\Models\Application;
use Illuminate\Http\Request;
class ApplicationController{
 function index(Request $r){return Application::where('user_id',$r->user()->id)->latest()->paginate(20);}
 function store(Request $r){$d=$r->validate(['cv_version_id'=>'nullable|integer','external_job_id'=>'nullable|string|max:255','title'=>'required|string|max:255','company'=>'required|string|max:255','url'=>'required|url:https|max:2000','job_description'=>'nullable|string|max:30000','status'=>'nullable|in:saved,prepared,applied,interview,rejected,offer','match_score'=>'nullable|integer|min:0|max:100','salary'=>'nullable|string|max:120','application_date'=>'nullable|date','reminder_at'=>'nullable|date','follow_up_at'=>'nullable|date','notes'=>'nullable|string|max:5000']);if(!empty($d['cv_version_id']))\App\Models\CvVersion::where('user_id',$r->user()->id)->findOrFail($d['cv_version_id']);$d['user_id']=$r->user()->id;if(($d['status']??'saved')==='applied')$d['applied_at']=now();$item=Application::create($d);\App\Services\AdminReview::record('application',$item);AuthController::audit($r,'application_saved',$r->user()->id);return response()->json($item,201);}
 function update(Request $r,Application $application){abort_unless($application->user_id===$r->user()->id,404);$d=$r->validate(['cv_version_id'=>'nullable|integer','status'=>'sometimes|in:saved,prepared,applied,interview,rejected,offer','salary'=>'nullable|string|max:120','application_date'=>'nullable|date','reminder_at'=>'nullable|date','follow_up_at'=>'nullable|date','notes'=>'nullable|string|max:5000']);if(!empty($d['cv_version_id']))\App\Models\CvVersion::where('user_id',$r->user()->id)->findOrFail($d['cv_version_id']);if(($d['status']??null)==='applied'&&!$application->applied_at)$d['applied_at']=now();$application->update($d);\App\Services\AdminReview::record('application',$application);AuthController::audit($r,'application_updated',$r->user()->id);return $application;}
 function destroy(Request $r,Application $application){abort_unless($application->user_id===$r->user()->id,404);\App\Services\AdminReview::forget('application',$application->id);$application->delete();return response()->noContent();}
}
