<?php
namespace App\Http\Controllers;
use App\Models\{Application,CareerReport,CvVersion,InterviewSession,JobWorkspace};
use App\Services\{AiGateway,AdminReview};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{DB,Http};
class CareerController{
 function dashboard(Request $r){$uid=$r->user()->id;$statuses=Application::where('user_id',$uid)->select('status',DB::raw('count(*) total'))->groupBy('status')->pluck('total','status');return ['applications'=>Application::where('user_id',$uid)->count(),'cv_versions'=>CvVersion::where('user_id',$uid)->count(),'interviews'=>InterviewSession::where('user_id',$uid)->count(),'workspaces'=>JobWorkspace::where('user_id',$uid)->count(),'statuses'=>$statuses,'reminders'=>Application::where('user_id',$uid)->whereNotNull('reminder_at')->where('reminder_at','>=',now())->orderBy('reminder_at')->limit(5)->get()];}
 function workspaces(Request $r){return JobWorkspace::where('user_id',$r->user()->id)->latest()->limit(100)->get();}
 function storeWorkspace(Request $r){$d=$r->validate(['title'=>'required|string|max:180','company'=>'nullable|string|max:180','job_url'=>'nullable|url:https|max:2000','job_description'=>'required|string|min:60|max:30000','cv_text'=>'required|string|min:30|max:30000']);$d['user_id']=$r->user()->id;$item=JobWorkspace::create($d);AdminReview::record('workspace',$item);AuthController::audit($r,'workspace_saved',$r->user()->id);return response()->json($item,201);}
 function versions(Request $r){return CvVersion::where('user_id',$r->user()->id)->latest()->limit(100)->get();}
 function storeVersion(Request $r){$d=$r->validate(['job_workspace_id'=>'nullable|integer','name'=>'required|string|max:180','content'=>'required|string|min:30|max:50000','source'=>'nullable|in:manual,ai,imported','builder_data'=>'nullable|array']);if(!empty($d['job_workspace_id']))JobWorkspace::where('user_id',$r->user()->id)->findOrFail($d['job_workspace_id']);$d['user_id']=$r->user()->id;$item=CvVersion::create($d);AdminReview::record('cv',$item);AuthController::audit($r,'cv_saved',$r->user()->id);return response()->json($item,201);}
 function destroyVersion(Request $r,CvVersion $version){abort_unless($version->user_id===$r->user()->id,404);AdminReview::forget('cv',$version->id);$version->delete();return response()->noContent();}
 function analytics(Request $r){$q=Application::where('user_id',$r->user()->id);$total=(clone $q)->count();$counts=(clone $q)->select('status',DB::raw('count(*) total'))->groupBy('status')->pluck('total','status');$interviews=(int)($counts['interview']??0);$offers=(int)($counts['offer']??0);return ['total'=>$total,'by_status'=>$counts,'interview_rate'=>$total?round(($interviews+$offers)/$total*100,1):0,'offer_rate'=>$total?round($offers/$total*100,1):0,'with_cv_version'=>(clone $q)->whereNotNull('cv_version_id')->count(),'without_cv_version'=>(clone $q)->whereNull('cv_version_id')->count(),'recent'=>(clone $q)->latest()->limit(20)->get()];}
 function recruiterView(Request $r,AiGateway $ai){$d=$this->documents($r);return $this->report($r,$ai,'recruiter_view',"Review this CV as a recruiter spending only 10-20 seconds. Never invent facts. Return: FIRST IMPRESSION, WHAT STANDS OUT, HARD-TO-FIND INFORMATION, RED FLAGS OR CONFUSION, and 5 FAST FIXES.\n\nCV:\n{$d['cv_text']}\n\nTARGET JOB:\n{$d['job_description']}",$d);}
 function tailorCv(Request $r,AiGateway $ai){$d=$this->documents($r,true);$prompt="Rewrite this CV for {$d['title']} at ".(($d['company']??'')?:'the company').". Preserve all facts and never invent experience, skills, dates, metrics, employers or education. Improve ordering, summary, bullets and truthful job keywords. Keep an ATS-friendly plain-text structure. Return only the complete tailored CV, ready to edit, with no commentary.\n\nORIGINAL CV:\n{$d['cv_text']}\n\nJOB:\n{$d['job_description']}";return $this->report($r,$ai,'tailor_cv',$prompt,$d);}
 function applicationPack(Request $r,AiGateway $ai){$d=$this->documents($r,true);$prompt="Create a complete truthful application pack for {$d['title']} at ".(($d['company']??'')?:'the company').". Never invent experience, skills, metrics, employers or education. Use only the CV and job text. Return exactly these sections: TAILORED CV, COVER LETTER, RECRUITER MESSAGE, INTERVIEW QUESTIONS, KEY JOB NOTES. Keep every section practical and ready to edit.\n\nCV:\n{$d['cv_text']}\n\nJOB:\n{$d['job_description']}";return $this->report($r,$ai,'application_pack',$prompt,$d);}
 function skillGap(Request $r,AiGateway $ai){$d=$this->documents($r);$prompt="Build a realistic skill-gap roadmap from this CV and job. Separate ALREADY HAVE, MISSING OR WEAK, PRIORITY ORDER, WHY EACH SKILL MATTERS, 30-DAY PLAN, and MINI-PROJECT IDEAS. Do not claim a skill is missing if the CV proves it. Do not promise hiring outcomes.\n\nCV:\n{$d['cv_text']}\n\nJOB:\n{$d['job_description']}";return $this->report($r,$ai,'skill_gap',$prompt,$d);}
 function portfolio(Request $r,AiGateway $ai){$d=$r->validate(['cv_text'=>'required|string|min:30|max:30000','job_description'=>'required|string|min:60|max:30000','github_url'=>'nullable|url:https|max:2000','portfolio_url'=>'nullable|url:https|max:2000','projects'=>'nullable|string|max:15000']);$repos=[];$github=$d['github_url']??'';$parts=$github?parse_url($github):[];if(($parts['host']??'')==='github.com'&&!empty($parts['path'])){$username=explode('/',trim($parts['path'],'/'))[0]??'';if(preg_match('/^[A-Za-z0-9-]{1,39}$/',$username)){try{$response=Http::timeout(12)->withHeaders(['User-Agent'=>'CVPilot-AI'])->get("https://api.github.com/users/{$username}/repos",['per_page'=>30,'sort'=>'updated']);if($response->successful())$repos=collect($response->json())->map(fn($repo)=>['name'=>$repo['name']??'','description'=>$repo['description']??null,'language'=>$repo['language']??null,'topics'=>$repo['topics']??[],'stars'=>$repo['stargazers_count']??0,'fork'=>$repo['fork']??false])->all();}catch(\Throwable){}}}$prompt="Analyze the supplied professional portfolio or work examples against the job. Public GitHub repository metadata is included when available; do not claim you inspected source code. Portfolio links are not fetched, so use only supplied project details. Return: BEST PROJECTS TO FEATURE, EVIDENCE MISSING, GITHUB/PORTFOLIO IMPROVEMENTS, and PROJECT IDEAS. Never invent repository content.\nGitHub: ".($github?:'not supplied')."\nPublic repository metadata:\n".json_encode($repos)."\nPortfolio: ".($d['portfolio_url']??'not supplied')."\nProject details:\n".($d['projects']??'none')."\n\nCV:\n{$d['cv_text']}\n\nJOB:\n{$d['job_description']}";$d['github_repositories']=$repos;return $this->report($r,$ai,'portfolio_analysis',$prompt,$d);}
 function followUp(Request $r,AiGateway $ai){$d=$r->validate(['type'=>'required|in:follow_up,thank_you,recruiter_message','name'=>'nullable|string|max:120','title'=>'required|string|max:180','company'=>'required|string|max:180','context'=>'nullable|string|max:5000','tone'=>'nullable|in:professional,warm,confident']);$prompt="Write a concise {$d['type']} message with a ".($d['tone']??'professional')." tone for {$d['title']} at {$d['company']}. Use only supplied context, no invented claims. Return a subject line when appropriate, then the message only. Sender: ".($d['name']??'[Your name]')."\nContext:\n".($d['context']??'');return $this->report($r,$ai,'follow_up',$prompt,$d);}
 function diagnostic(Request $r,AiGateway $ai){$apps=Application::where('user_id',$r->user()->id)->latest()->limit(100)->get(['title','company','status','match_score','cv_version_id','application_date','notes']);abort_if($apps->count()<3,422,'Add at least 3 applications before running this diagnosis.');$prompt="Analyze these application outcomes and identify patterns that may explain low interview response. Treat every conclusion as a diagnostic indicator, not a fact. Use headings: OBSERVED PATTERNS, POSSIBLE CAUSES, WHAT THE DATA CANNOT PROVE, NEXT 3 EXPERIMENTS, and WHAT TO TRACK NEXT. Do not blame protected traits and do not promise outcomes.\n\nAPPLICATION DATA:\n".$apps->toJson();return $this->report($r,$ai,'career_diagnostic',$prompt,['applications'=>$apps->toArray()]);}
 function startInterview(Request $r,AiGateway $ai){$d=$this->documents($r,true);$prompt="Act as a structured interviewer for {$d['title']} at ".(($d['company']??'')?:'the company').". Read the CV and job. Ask exactly one relevant interview question. Do not score. Return only the question.\nCV:\n{$d['cv_text']}\nJOB:\n{$d['job_description']}";$result=$ai->chat($prompt,'interview',$r->user()->id);$session=InterviewSession::create(['user_id'=>$r->user()->id,'title'=>$d['title'],'company'=>$d['company']??null,'cv_text'=>$d['cv_text'],'job_description'=>$d['job_description'],'transcript'=>[['role'=>'assistant','content'=>$result['answer']]]]);AdminReview::record('interview',$session);AuthController::audit($r,'interview_started',$r->user()->id);return ['session_id'=>$session->id,'question'=>$result['answer']];}
 function replyInterview(Request $r,InterviewSession $session,AiGateway $ai){abort_unless($session->user_id===$r->user()->id,404);abort_unless($session->status==='active',422,'This interview is already completed.');$d=$r->validate(['answer'=>'required|string|min:2|max:6000']);$transcript=$session->transcript;$transcript[]=['role'=>'user','content'=>$d['answer']];$prompt="Continue this mock interview. Give brief useful feedback on the candidate's last answer without a numeric score, then ask exactly one new question. Return with headings FEEDBACK and NEXT QUESTION. Never invent facts.\nCV:\n{$session->cv_text}\nJOB:\n{$session->job_description}\nTRANSCRIPT:\n".json_encode($transcript);$result=$ai->chat($prompt,'interview',$r->user()->id);$transcript[]=['role'=>'assistant','content'=>$result['answer']];$session->update(['transcript'=>$transcript]);AdminReview::record('interview',$session);return ['reply'=>$result['answer']];}
 function finishInterview(Request $r,InterviewSession $session,AiGateway $ai){abort_unless($session->user_id===$r->user()->id,404);if($session->status==='completed')return ['feedback'=>$session->feedback];$prompt="Give final mock-interview feedback without a numeric score. Use headings: STRONG ANSWERS, ANSWERS TO IMPROVE, MISSING EVIDENCE, COMMUNICATION FEEDBACK, and NEXT PRACTICE STEPS. Base everything only on this transcript and CV.\nCV:\n{$session->cv_text}\nJOB:\n{$session->job_description}\nTRANSCRIPT:\n".json_encode($session->transcript);$result=$ai->chat($prompt,'interview',$r->user()->id);$session->update(['feedback'=>$result['answer'],'status'=>'completed']);AdminReview::record('interview',$session);AuthController::audit($r,'interview_completed',$r->user()->id);return ['feedback'=>$result['answer']];}

 function library(Request $r){
  $uid=$r->user()->id;$r->validate(['page'=>'nullable|integer|min:1','kind'=>'nullable|in:cv,interview,workspace,report,application,upload']);
  $models=['cv'=>CvVersion::class,'interview'=>InterviewSession::class,'workspace'=>JobWorkspace::class,'report'=>CareerReport::class,'application'=>Application::class,'upload'=>\App\Models\CvDocument::class];
  $counts=[];foreach($models as $key=>$model){$q=$model::where('user_id',$uid);if($key==='upload')$q->where('expires_at','>',now());$counts[$key]=$q->count();}
  $kind=$r->input('kind','cv');$q=$models[$kind]::where('user_id',$uid);if($kind==='upload')$q->where('expires_at','>',now());
  return ['counts'=>$counts,'items'=>$q->latest()->paginate(12)];
 }
 function version(Request $r,CvVersion $version){abort_unless($version->user_id===$r->user()->id,404);return $version;}
 function updateVersion(Request $r,CvVersion $version){abort_unless($version->user_id===$r->user()->id,404);$d=$r->validate(['name'=>'required|string|max:180','content'=>'required|string|min:30|max:50000','builder_data'=>'nullable|array']);$version->update($d);AdminReview::record('cv',$version);return $version;}
 function interview(Request $r,InterviewSession $session){abort_unless($session->user_id===$r->user()->id,404);return $session;}
 function workspace(Request $r,JobWorkspace $workspace){abort_unless($workspace->user_id===$r->user()->id,404);return $workspace;}
 private function documents(Request $r,bool $identity=false):array{$rules=['cv_text'=>'required|string|min:30|max:30000','job_description'=>'required|string|min:60|max:30000'];if($identity)$rules+=['title'=>'required|string|max:180','company'=>'nullable|string|max:180'];return $r->validate($rules);}
 private function report(Request $r,AiGateway $ai,string $type,string $prompt,array $input):array{$result=$ai->chat($prompt,$type,$r->user()->id);$row=CareerReport::create(['user_id'=>$r->user()->id,'type'=>$type,'input'=>$input,'output'=>$result['answer']]);AdminReview::record('report',$row);AuthController::audit($r,$type.'_generated',$r->user()->id);return $result+['report_id'=>$row->id];}
}
